using Microsoft.AspNetCore.Mvc;
using RacingEventManagement.Service;

namespace RacingEventManagement.Controllers
{
    [ApiController]
    [Route("[controller]/[action]")]
    public class RacingController : ControllerBase
    {
        private readonly ILogger<RacingController> _logger;
        private readonly RaceService _raceService;
        private readonly ParticipantService _participantService;

        public RacingController(ILogger<RacingController> logger, RaceService raceService, ParticipantService participantService)
        {
            _logger = logger;
            _raceService = raceService;            _participantService = participantService;   

        }

        [HttpGet]   
        public void AllAboutRaces()
        {
           //_raceService.CreateRacesWithAutoGeneratedIds();
           _raceService.GetAllRaces();

            _raceService.PerformingDifferentUpdates();
        }

        [HttpGet]
        public void AllAboutParticipants()
        {
            _participantService.AddParticipantsAndModifyThem();
        }
    }
}
