using Microsoft.AspNetCore.Mvc;
using RacingEventManagement.Service;

namespace RacingEventManagement.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class RacingController : ControllerBase
    {
        private readonly ILogger<RacingController> _logger;
        private readonly RaceService _raceService;

        public RacingController(ILogger<RacingController> logger, RaceService raceService)
        {
            _logger = logger;
            _raceService = raceService;
        }

        [HttpGet]   
        public void GetItRunning()
        {
           //_raceService.CreateRacesWithAutoGeneratedIds();
           _raceService.GetAllRaces();
        }
    }
}
